--관리자 테이블(관리자ID, 이름, 권한 등)
--회원 테이블(회원ID, 이름, 연락처, 결제정보 등)
--시설 테이블(시설ID, 위치, 시설정보 등)
--예약 테이블(예약ID, 회원ID, 시설ID, 예약일시, 대여기간)

/* 
TABLE MEMBER
유저번호, 아이디, 패스워드 이름, 관리자(BOOLEAN), 연락처, 생성시간

TABLE 시설 FACILITY
시설번호, 시설이름, 시설위치, 생성일

TABLE 예약 Reservation
예약번호, 회원아이디, 시설아이디, 예약일, 대여기간

TABLE 후기 REVIEW


이용 여부 처음에는 NULL 값으로 갖고 있다가
이용 완료하면 트리거로 불린값 전달

*/

SELECT * FROM R_FAC;
DESC R_USER;


----------------------------------------------------------------------
ALTER TABLE R_USER ADD CONSTRAINT R_USER_UNIQUE UNIQUE(USERID);

ALTER TABLE R_RES
ADD CONSTRAINT USER_ID_FK
FOREIGN KEY (USERID) REFERENCES R_USER(USERID);
----------------------------------------------------------------------

ALTER TABLE R_RES ADD CONSTRAINT R_FAC_UNIQUE UNIQUE(FACNAME);

ALTER TABLE R_FAC
ADD CONSTRAINT FAC_FK
FOREIGN KEY (FACNO) REFERENCES R_RES(RESNO);

ALTER TABLE R_RES
ADD CONSTRAINT FAC_FK
FOREIGN KEY (RESNO) REFERENCES R_FAC(FACNO);

----------------------------------------------------------------------
ALTER TABLE R_REVIEW ADD CONSTRAINT R_REVIEW_UNIQUE UNIQUE(FACNAME);

ALTER TABLE R_FAC ADD CONSTRAINT R_FAC_UNIQUE_FACNAME UNIQUE(FACNAME);

ALTER TABLE R_FAC
ADD CONSTRAINT FAC_REVIEW_FK
FOREIGN KEY (FACNAME) REFERENCES R_REVIEW(FACNAME);

ALTER TABLE R_REVIEW
ADD CONSTRAINT FAC_REVIEW_FK
FOREIGN KEY (FACNAME) REFERENCES R_FAC(FACNAME);
-------------
ALTER TABLE R_REVIEW 
ADD CONSTRAINT REVIEW_USER_FK FOREIGN KEY (USERID) REFERENCES R_USER(USERID);
-------------------


SELECT * FROM r_user;


INSERT INTO "RENTAL"."R_FAC" (FACNO, FACNAME, FACADDR, CREATE_AT) VALUES ('1', '고척스카이돔', '서울특별시 구로구 경인로 430', TO_DATE('2024-03-13 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "RENTAL"."R_FAC" (FACNO, FACNAME, FACADDR, CREATE_AT) VALUES ('2', '보라매공원축구장', '서울특별시 동작구 신대방동 395', TO_DATE('2024-03-13 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "RENTAL"."R_FAC" (FACNO, FACNAME,  FACADDR, CREATE_AT) VALUES ('3', '반포종합운동장', '서울특별시 서초구 신반포로 30', TO_DATE('2024-03-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "RENTAL"."R_FAC" (FACNO, FACNAME, FACADDR, CREATE_AT) VALUES ('4', '이촌한강공원', '서울특별시 용산구 이촌로72길 62', TO_DATE('2024-03-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "RENTAL"."R_FAC" (FACNO, FACNAME, FACADDR, CREATE_AT) VALUES ('5', '탄천축구장', '서울특별시 송파구 삼학사로2길 49', TO_DATE('2024-03-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

commit;


CREATE SEQUENCE r_fac_seq
START WITH 6
INCREMENT BY 1
MAXVALUE 99999999999999
MINVALUE 0
NOCYCLE
NOCACHE;

CREATE SEQUENCE r_user_seq
START WITH 6
INCREMENT BY 1
MAXVALUE 99999999999999
MINVALUE 0
NOCYCLE
NOCACHE;

-------------------


CREATE SEQUENCE r_res_seq
START WITH 1
INCREMENT BY 1
MAXVALUE 99999999999999
MINVALUE 0
NOCYCLE
NOCACHE;

CREATE SEQUENCE r_review_seq
START WITH 1
INCREMENT BY 1
MAXVALUE 99999999999999
MINVALUE 0
NOCYCLE
NOCACHE;

select * from r_fac;

select * from r_fac;
desc r_fac;


ALTER USER rental IDENTIFIED BY 1111;


ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;



CREATE OR REPLACE TRIGGER TRG_DELETE_USER
BEFORE
    DELETE ON r_user
    FOR EACH ROW
    
BEGIN
    UPDATE r_review SET userId = '(탈퇴한회원)' WHERE userId = :OLD.userId;
    DELETE FROM r_res WHERE userId = :OLD.userId;
END;
/



rollback;