services:
  mongodb:
    image: mongo
    container_name: mongoDb
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aibayo
      - MONGO_INITDB_ROOT_PASSWORD=aibayo
  mongo-express:
    image: mongo-express
    container_name: mongoExpress
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=aibayo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=aibayo
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo: {}