services:
    mongo-express:
        container_name: mongoExpress
        environment: '[ME_CONFIG_MONGODB_ADMINUSERNAME=aibayo, ME_CONFIG_MONGODB_ADMINPASSWORD=aibayo,
            ME_CONFIG_MONGODB_SERVER=mongodb]'
        image: mongo-express
        ports: '[8081:8081]'
        restart: always
    mongodb:
        container_name: mongoDb
        environment: '[MONGO_INITDB_ROOT_USERNAME=aibayo, MONGO_INITDB_ROOT_PASSWORD=aibayo]'
        image: mongo
        ports: '[27017:27017]'
        volumes: '[mongo:/data]'
